### ISSUE TITLE
Questions about the JSONPATH code?

### ISSUE THREAD

**Issue by danielpygo** [LiliC/travis-minikube#20]
`- JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl -n default get pods -lapp=travis-example -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1;echo "waiting for travis-example deployment to be available"; kubectl get pods -n default; done`

First and foremost, thanks for the repo example . . 
I am having a hard time repurposing this for my needs.
I would like to check that certain pods and operators are able to deploy and delete successfully in my end to end testing . 

I was hoping you could go line by line and breakdown the logic of each statement.
Particularly the first two lines I don't understand.
1. `'{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'`

2. `until kubectl -n default get pods -lapp=travis-example -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; `

Questions like these come to mind: the flag -lapp this is a selector right? and what does `"$JSONPATH" 2>&1 | grep -q "Ready=True";` mean (2>&1?)?Where did the variable &1 come from?

Thanks
Daniel Moore

**Comment by LiliC** [comment]
@danielpygo 
The code snippet you were referring to just checks that minikube created a Kubernetes cluster where we can create and run resources, we do this by running a pod and then checking that pod exists and is running in the cluster. https://github.com/LiliC/travis-minikube/blob/ab3e2df23e2a87ddd3fab20fe007e4c86e3f3d98/.travis.yml#L25-L26

> Questions like these come to mind: the flag -lapp this is a selector right? 

Yes, it's the label selector, we use it to get the correct pod we just created and make sure it's running.

> mean (2>&1?)?Where did the variable &1 come from?

This is nothing specific to kubernetes but more to do with unix file descriptions. 
https://stackoverflow.com/questions/818255/in-the-shell-what-does-21-mean

> I would like to check that certain pods and operators are able to deploy and delete successfully in my end to end testing .

You would just replace [this part](https://github.com/LiliC/travis-minikube/blob/ab3e2df23e2a87ddd3fab20fe007e4c86e3f3d98/.travis.yml#L19-L28) with your kubectl commands that deploy/create pods and operators and then check they are running in a similiar way. Best is to deploy locally on minikube and then just copy paste commands there and error out. You can also use the go approach and make the full end-to-end test suite.

Hopefully that makes sense, otherwise feel free to ask if you have any other questions.

**Comment by danielpygo** [comment]
thanks! and I just found this resource: https://kubernetes.io/docs/reference/kubectl/jsonpath/
It is making more sense now.

Ok cool it did look like a selector.

> This is nothing specific to kubernetes but more to do with unix file descriptions.
Ah I'll look into this !

> You can also use the go approach and make the full end-to-end test suite.
Could you please expand on this or give me more context or a link? I probably have seen example of this end-to-end test suite on Github

**Comment by LiliC** [comment]
@danielpygo 
> Oh, could you please expand on this or give me more context/a link? I have written go unit tests, but not for end-to-end kubernetes testing

Sure, kubernetes exposes a client in go, that you can levarage to use when writing your end-to-end tests. (Think there are other languages, depending on your projects main used language.)

We have an e2e framework helper in the operator-sdk you can have a look. https://github.com/operator-framework/operator-sdk/blob/master/doc/test-framework/writing-e2e-tests.md We also use it for operator-sdk [e2e](https://github.com/operator-framework/operator-sdk/tree/master/test/e2e). 

If you don't want to use that framework you can look at other operators, for example https://github.com/coreos/prometheus-operator/tree/master/test/e2e

**Comment by danielpygo** [comment]
Oh right client-go. and okay thanks, I will look into that @LiliC!
